Vagrant.configure("2") do |config|
  
  config.vm.box = "boxcycler/linuxmint-19-mate-64bit-v2-release"
  config.vm.box_version = "19.0.0"

  config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.name = "dev_java_v1"
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        # TODO: speed up 3d: sudo apt-get install compizconfig-settings-manager && ccsm
        # TODO: after starting ccsm enable opengl+composite
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--monitorcount", "2"]
        vb.customize ["modifyvm", :id, "--memory", "8000"]
        vb.customize ["modifyvm", :id, "--cpus", "6"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["storagectl", :id, "--name", "SATA", "--hostiocache", "on"]
        vb.gui = true
    end
end
