Vagrant.configure("2") do |config|
    config.vm.box = "boxcycler/linuxmint-19-mate-64bit-v2-release"
    config.vm.box_version = "19.0.0"

    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.name = "dev_java_v1"
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        # TODO: speed up 3d: sudo apt-get install compizconfig-settings-manager && ccsm
        # TODO: after starting ccsm enable opengl+composite
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--monitorcount", "2"]
        vb.customize ["modifyvm", :id, "--memory", "6000"]
        vb.customize ["modifyvm", :id, "--cpus", "4"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["storagectl", :id, "--name", "SATA", "--hostiocache", "on"]
        vb.gui = true
    end

    config.vm.provision "shell", inline: <<-SHELL 		

        ############################################
        # BASIC INIT                               #
        ############################################
        VBOX_VERSION=#{ENV['VBOX_VERSION']};    		    
	VAGRANT_USER_HOME="/home/vagrant"
	DEBIAN_FRONTEND=noninteractive
        apt update  

        # disable sudo-password for vagrant-user
    	echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers 
        
        # setup german keyboard
	localectl set-keymap de
	echo "" >> $VAGRANT_USER_HOME/.bashrc    
	echo 'setxkbmap de'  >> $VAGRANT_USER_HOME/.bashrc

	mkdir -p $VAGRANT_USER_HOME/scripts

        ############################################
        # VBOX ADDITIONS                           #
        ############################################
	cd $VAGRANT_USER_HOME/scripts
	curl -O https://raw.githubusercontent.com/neocdtv/vagrant-boxes/master/scripts/setup_vbox_additions.sh
	chmod a+x setup_vbox_additions.sh
	./setup_vbox_additions.sh $VAGRANT_USER_HOME $VBOX_VERSION
	
        ############################################
        # CRIU                                     #
        ############################################
	cd $VAGRANT_USER_HOME/scripts
	curl -O https://raw.githubusercontent.com/neocdtv/vagrant-boxes/master/scripts/setup_criu.sh
	chmod a+x setup_criu.sh
	./setup_criu.sh $VAGRANT_USER_HOME
        
        # add settings for every jdk and maven and convinient switches in bashrs
        # TODO: jdk hotspot 8,9,11,12,13,14
        # TODO: jdk openj9 8,9,11,12,13,14
        # TODO: jdk graalvm        
        # TODO: maven  

	SHELL
end
