Vagrant.configure("2") do |config|
    config.vm.box = "boxcycler/linuxmint-19-mate-64bit-v2-release"
    config.vm.box_version = "19.0.0"

    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.name = "dev_java_v1"
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        # TODO: speed up 3d: sudo apt-get install compizconfig-settings-manager && ccsm
        # TODO: after starting ccsm enable opengl+composite
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--monitorcount", "2"]
        vb.customize ["modifyvm", :id, "--memory", "8000"]
        vb.customize ["modifyvm", :id, "--cpus", "6"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["storagectl", :id, "--name", "SATA", "--hostiocache", "on"]
        vb.gui = true
    end

    config.vm.provision "shell", inline: <<-SHELL 		

        ############################################
        # BASIC INIT                            
        ############################################
	export VBOX_VERSION=#{ENV['VBOX_VERSION']};    		    
	export USER_HOME="/home/vagrant"
	export DEBIAN_FRONTEND=noninteractive
	export SCRIPTS_DIR=$USER_HOME/scripts
	export PATH="$SCRIPTS_DIR:$PATH"
	mkdir -p "$SCRIPTS_DIR"
	# disable sudo-password for vagrant-user
    	echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers 
        
	apt update  
	
	cd $SCRIPTS_DIR
	curl -O https://raw.githubusercontent.com/neocdtv/vagrant-boxes/master/scripts/run_script.sh
	chmod a+x ./run_script.sh
	cd $USER_HOME
	
        
	############################################
        # LOCALIZATIONS                           
        ############################################
	run_script.sh setup_keyboard_de.sh

        ############################################
        # VBOX ADDITIONS                           
        ############################################
	run_script.sh setup_vbox_additions.sh
	
        ############################################
        # CRIU                                     
        ############################################
	run_script.sh setup_criu.sh
	
	############################################
        # DOCKER
        ############################################
	run_script.sh setup_docker.sh

	############################################
        # JDK 11 - OPENJ9
        ############################################
	run_script.sh setup_jdk_11_openj9.sh
	
	############################################
        # JDK 11 - HOTSPOT
        ############################################
	run_script.sh setup_jdk_11_hotspot.sh

	############################################
        # MAVEN
        ############################################
	run_script.sh setup_maven.sh
	
	############################################
        # INTELLIJ
        ############################################
	run_script.sh setup_intellij.sh
	
	############################################
        # SciTE
        ############################################
	run_script.sh setup_scite.sh
	
	############################################
        # PAYARA MICRO
        ############################################
	run_script.sh setup_payara_micro.sh
	
	############################################
        # FIX PERMISSIONS
        ############################################	
	chmod -R a+rwx $USER_HOME/scripts
	chmod -R a+rwx $USER_HOME/Projects
	chmod -R a+rwx $USER_HOME/Apps
	
	apt install inotify-tools
	
	# TODO: .bashrc
	# F1 - make all
	# F2 - make database
	# F3 - make build-app 
	# F4 - make run-app
	# F4 - make unit-tests

        # TODO:
	# add functions dump and restore using criu for payara-micro
	# add payara micro
	# add default jee8 project? 
	# vscode with launcher - dont use snap its slower

	SHELL
end
