Vagrant.configure("2") do |config|
    config.vm.box = "boxcycler/linuxmint-19-mate-64bit-v2-release"
    config.vm.box_version = "19.0.0"

    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.name = "dev_java_v1"
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        # TODO: speed up 3d: sudo apt-get install compizconfig-settings-manager && ccsm
        # TODO: after starting ccsm enable opengl+composite
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--monitorcount", "2"]
        vb.customize ["modifyvm", :id, "--memory", "8000"]
        vb.customize ["modifyvm", :id, "--cpus", "6"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["storagectl", :id, "--name", "SATA", "--hostiocache", "on"]
        vb.gui = true
    end

    config.vm.provision "shell", inline: <<-SHELL 		

        ############################################
        # BASIC INIT                            
        ############################################
	export VBOX_VERSION=#{ENV['VBOX_VERSION']};    		    
	export HOME="/home/vagrant"
	export DEBIAN_FRONTEND=noninteractive
	
	# disable sudo-password for vagrant-user
    	echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers 
        
	apt update  
	apt install git
	
	git clone https://github.com/neocdtv/linux-setup.git
	cd linux-setup/dev-java
	chmod a+x ./setup.sh
	
	############################################
        # FIX PERMISSIONS
        ############################################	
	chmod -R a+rwx $USER_HOME/scripts
	chmod -R a+rwx $USER_HOME/Projects
	chmod -R a+rwx $USER_HOME/Apps
	
	apt install -y inotify-tools
	apt install tree

	
	# TODO: .bashrc
	# F1 - make all
	# F2 - make database
	# F3 - make build-app 
	# F4 - make run-app
	# F4 - make unit-tests

        # TODO:
	# add functions dump and restore using criu for payara-micro
	# vscode with launcher - dont use snap its slower

	SHELL
end
